### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by DocSunset** [mathiasbredholt/libmapper_arduino#11]
Hi @mathiasbredholt . I notice that this repo is licensed under GPL 3.0 or later, which is notably more restrictive than the LGPL 2.1 or later used by liblo and libmapper. I don't have any issue with this (I'm all for a good strong copyleft license), but wanted to verify that this was your intention, since I also saw that e.g. [the T-Stick firmware is marked as MIT licensed](https://github.com/IDMIL/T-Stick/blob/main/firmware/LICENSE) while using this library, which would appear to be, well, not allowed. Hence: is this library inadvertently more strongly licensed than intended, or is the T-Stick firmware inadvertently violating the libmapper-arduino terms of use?

**Comment by badebold** [comment]
Hi @DocSunset, this is unintentional for my part and I'd like to change to LGPL if all contributors agree? @ChristianFrisson @filipecalegario @malloch

**Comment by malloch** [comment]
I'm in favour of switching to LGPL

**Comment by filipecalegario** [comment]
I'm in favour of switching to LGPL, as well.

Filipe Calegario
filipecalegario.net

**Comment by ChristianFrisson** [comment]
Also OK to change to LGPL!
