### ISSUE TITLE
fatal error: ../../../lwip/src/include/lwip/inet.h: No such file or directory

### ISSUE THREAD

**Issue by filipecalegario** [mathiasbredholt/libmapper_arduino#3]
I'm trying to compile libmapper_arduino following the instructions in README.md.
After running make and waiting for a little,  I received the following error:

![Screenshot 2019-10-28 23 59 09](https://user-images.githubusercontent.com/299057/67734331-87084480-f9df-11e9-9a67-fbcfcd00882e.png)

**Comment by badebold** [comment]
Thanks for posting the error. I will look into it, I'm not very experienced in writing Makefiles so I'm probably doing something wrong.

**Comment by badebold** [comment]
After spending most of the day understanding this error, I realized that I changed that particular file some weeks ago.
If you change the file inet.h from
```
#ifndef INET_H_
#define INET_H_

#include "../../../lwip/src/include/lwip/inet.h"

#endif /* INET_H_ */
```
to
```
#ifndef INET_H_
#define INET_H_

#include "lwip/inet.h"

#endif /* INET_H_ */
```
it should work. I issued a pull request to the main arduino-esp32 repository.

**Comment by badebold** [comment]
Let's wait with closing the issue until the arduino-esp32 core gets updated with the fix.

**Comment by badebold** [comment]
https://github.com/espressif/arduino-esp32/pull/3425

**Comment by badebold** [comment]
This issue has been resolved in ESP-IDF
